apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-app
  namespace: argocd
spec:
    source:
        repoURL: https://github.com/devopslalitharwate-sudo/argocd_kustomization
        targetRevision: main
        path: apps/overlays/prod
    syncPolicy:
        automated: null
        syncOptions:
            - CreateNamespace=true
    destination:
        namespace: new-app-prod
